### ISSUE TITLE
Delonghi protocol

### ISSUE THREAD

**Issue by fhempy** [prototux/delonghi-re#1]
Hi,
great project! I hope that you can find out the details of the protocol as I would also like to remotely control my machine :)
Have you seen this paper on delonghi protocol:
https://comsys.ovgu.de/comsys_media/thesis/finished/BSc/2018_Fabian+Off+_+Reverse_engineering+a+DeLonghi+Coffee+Maker+to+precisely+bill+Coffee+Consumption-p-332.pdf
Maybe it helps to reverse engineer the protocol.

I'm looking forward to further updates on the project 👍

**Comment by prototux** [comment]
Hello, I've seen it, but it does apply to older Delonghi machines, as machines changes the link type between the power and UI boards as they update them.

The ECAM 23.450 i'm RE'ing uses an UART+I2C link, not an SPI link.
The current status of this project can be found here: https://github.com/prototux/delonghi-re/tree/reimplem-clean/ecam23.450_displayboard_reverse/reimplem it's a manual decompilation/reimplementation of the UI board's firmware. the main part of the protocol is known, but the logic isn't yet (as it's 2 big functions with giant switch in them).

The protocol can be found here: https://github.com/prototux/delonghi-re/blob/reimplem-clean/ecam23.450_displayboard_reverse/reimplem/powerboard_com.c
